language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
ruby: 2.2.0
before_install:
- pip install vcstool
- sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
- wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
- sudo apt-get update
- wget https://raw.githubusercontent.com/ignitionrobotics/ign-gazebo/master/docker/scripts/install_common_deps.sh
- wget https://raw.githubusercontent.com/ignitionrobotics/ign-gazebo/master/docker/scripts/install_ign_deps.sh
- bash install_common_deps.sh
- bash install_ign_deps.sh
script:
- mkdir -p ignition_workspace/src
- cd ignition_workspace/src
- wget https://raw.githubusercontent.com/ignition-tooling/gazebodistro/master/collection-citadel.yaml
- vcs import < collection-citadel.yaml
- cd ..
- colcon build --merge-install
- colcon test --merge-install
