dist: bionic
os:
- linux
services:
- docker

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ignition-citadel-builder .
    - docker images
    - docker tag ignition-citadel-builder $DOCKER_USERNAME/ignition-citadel-builder
    - docker push $DOCKER_USERNAME/ignition-citadel-builder
  - stage: ign-cmake
    script:
    - docker run --name builder -e BINTRAY_API_KEY=$BINTRAY_API_KEY $DOCKER_USERNAME/ignition-citadel-builder bash
    - docker exec builder bash build_and_deploy.sh ignitionrobotics ign-cmake ign-cmake2
  - stage: ign-math
    script:
    - docker run --name builder -e BINTRAY_API_KEY=$BINTRAY_API_KEY $DOCKER_USERNAME/ignition-citadel-builder bash
    - docker exec builder bash download_and_install.sh ign-cmake2
    - docker exec builder bash build_and_deploy.sh ignitionrobotics ign-math ign-math6

