dist: bionic
os:
- linux
services:
- docker

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ignition-citadel-builder .
    - docker images
    - docker tag ignition-citadel-builder $DOCKER_USERNAME/ignition-citadel-builder
    - docker push $DOCKER_USERNAME/ignition-citadel-builder
  - stage: ign-cmake
    script:
    - docker run -it
    - bash build.sh ignitionrobotics ign-cmake ign-cmake2

