dist: bionic
os:
- linux
services:
- docker

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ignition-citadel-builder .
    - docker images
    - docker tag ignition-citadel-builder $DOCKER_USERNAME/ignition-citadel-builder
    - docker push $DOCKER_USERNAME/ignition-citadel-builder
  - stage: ign-cmake
    script:
    - docker run -e BINTRAY_API_KEY=$BINTRAY_API_KEY --rm $DOCKER_USERNAME/ignition-citadel-builder bash build_ign_cmake.sh

