dist: bionic
os:
- linux
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ignition-citadel-builder .
    - docker images
    - docker tag ignition-citadel-builder $DOCKER_USERNAME/ignition-citadel-builder
    - docker push $DOCKER_USERNAME/ignition-citadel-builder
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/ignition-citadel-builder echo hola
env:
  global:
  - secure: Z77Xk0wvDBOPrdOIAHwVA7cTygIOhMF7XJZcEHcAKPAqVi21VG5Kifgsx+vJXAS3Hpya4+6WPbfwTPicBZ9B2r/PrgmUBsewqJ37jzX3o72kreufV05/uEqp8Bp5sJ+yiBJUAnEu8UbzRMSh4+sJSbKkcHV2Rj3v+TWM/hym/ws8DtPgnHvxr0/ddcaNgcUZR7ymj0EDYu9Gazw2VDQSCVg3fSz8D5KUUNPe7bAocSN32WfkZdEnlPXcelzsuUczMuPxpwctx8pAlVXwrlgE4YE0AbLGfb+IjDqqTSiSzbkMmCeDe0rpuDfPEoFxKAXRkZw0cxlqA81Cy1+vgnc6JGSortAxcvqXWbL6h5Oyecb0exe8+CbItqD93OtDnMSOf7On9awToi3yrX50my9XYScbjADIlFyCwQuGtPnkD1Wvrtq2qdhXw/qjcnqBG2N1LBn+bAFxe7vF69L6sZyx7aWIFX7LDgp3ceg3gL1VQtnDntvvaOF0BX/LCiFViIxyr81rt9fSHU2A5mKTMp1wojfRv5DQuPFiUyYihNDXSMRLLyWmKdpldfLQuaVRSNSDJr/lsi+dEZOIxxHLifVNMLFPhEzjZx2upL+KNIAutu0SpiaJ48CD8oOsvJDATvI8aNpspb7MhpJBUkhzpp35cmgf4M8H4ar3Js8l2wSrA8Y=
  - secure: ZnRj/igY1UcD7NRw6OjNA1/yZAgSWTkV5ajRaAX3HFOg9ORUrly02pfIo31a0ZmGu2kkv1dCtRfFLVe5ItyR6RFJFVuQ2sALNa0nyvnt9V39uRCuAk/KP99GM75BKKpkkMuT//ZhATurtCUznoTHpklaHF8LzLrOR0bFFC1Eexlq5950hzoUAu/UF3TJrz02LgqO5uAV+C8oUZyrFGHUZqQKMtGlnJVAQF86HP4rGKjU5IHX1RbaalHNgUnpGYF9l636zOyZRFnnhiMbB3Ktg8igJvMmJ26YWpZtxuz8ljtD0tpWv88q3JXcgJDv2Wav0A/keD1fZILZciau3z6cNCpolbOMvmwlTsIb19QDRUt7fwIyFU2nzpuCXcxurEVVApybWHXkZ7nwdJdxE5A0MaDhtKtzeVxvh59lsVPRs/ReuRzfNABtbdK2es2XlwDC9XS86LWF4St5cfGnrvrXhfu7Xee2svH01fakaac/GDyf+m8FS+sQHogymmmhSN9mf57YhedHl6ocsrr0XAv8h0+u178F+2KJqT8Wv23jp1QFeS3MKGOhaDYhnkHPKAUabhiMEX6DJrMHo9qUkpIChrWG/CR9jmsMXv3p0/wg7GedrKC33RM8abwIbyP/plW3iEJSsvxl6NFO0Xxl8csjTCCRQhUtQ7Dcaa9tvYeabnI=
